### ISSUE TITLE
powershell-veeamallstat - Session Details missing

### ISSUE THREAD

**Issue by vMarkusK** [tdewin/randomsamples#1]
All Session Details (subsection) for a completed session is missing. 

![2017-08-25 22_05_18-vcd-lab](https://user-images.githubusercontent.com/16706362/29730942-bcf6a92a-89e2-11e7-9f79-bfafa23b2b70.png)

My Environment:
- PS 5.0
- Veeam 9.5 U1

**Comment by tdewin** [comment]
Did you click on the job itself? It collapses the details. The idea is that in a large environment you can have a quick overview over all jobs. 

Can you also attach the html if it does not work

**Comment by vMarkusK** [comment]
OK, this is embarrassing ... 

Report works as expected as you click on the Job. Thanks!
